// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadClasses():Promise<Array<string>>;

export function LoadScripts():Promise<Array<string>>;

export function StartBot(arg1:string,arg2:string):Promise<void>;

export function StopBot():Promise<void>;
