// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadClasses() {
  return window['go']['bot']['Bot']['LoadClasses']();
}

export function LoadScripts() {
  return window['go']['bot']['Bot']['LoadScripts']();
}

export function StartBot(arg1, arg2) {
  return window['go']['bot']['Bot']['StartBot'](arg1, arg2);
}

export function StopBot() {
  return window['go']['bot']['Bot']['StopBot']();
}
